### ISSUE TITLE
Indexing Service 任务管理的源码介绍

### ISSUE THREAD

**Issue by niko2020cc** [coolplaydata/coolplaydruid#4]
完成 Indexing Service 任务管理主要流程的源码介绍。

- 任务提交和指派
- 任务的执行
- 任务的结束

**Comment by niko2020cc** [comment]
已完成：

- [Indexing Service 根页面](https://github.com/coolplaydata/coolplaydruid/blob/dev/arch/indexing-service/indexing-service.md)
- [任务提交和指派](https://github.com/coolplaydata/coolplaydruid/blob/dev/arch/indexing-service/indexing-service-submit-task.md)

**Comment by liuheng720** [comment]
well done  👍

**Comment by niko2020cc** [comment]
已完成：

- [任务执行](https://github.com/coolplaydata/coolplaydruid/blob/dev/arch/indexing-service/indexing-service-run-task.md)

**Comment by niko2020cc** [comment]
已完成：
- [任务结束和清理](https://github.com/coolplaydata/coolplaydruid/blob/dev/arch/indexing-service/indexing-service-end-task.md)
